module.exports = {
  apps: [
    {
      name: "kawoukeravore-api",
      script: "./apps/api/src/server.js",
      cwd: "./",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "development",
        PORT: 4000,
      },
      env_production: {
        NODE_ENV: "production",
        PORT: 4000,
      },
      env_staging: {
        NODE_ENV: "staging",
        PORT: 4001,
      },
      log_file: "./logs/api-combined.log",
      out_file: "./logs/api-out.log",
      error_file: "./logs/api-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      max_memory_restart: "300M",
      restart_delay: 4000,
      max_restarts: 10,
      min_uptime: "10s",
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 10000,
      autorestart: true,
      watch: false,
      ignore_watch: ["node_modules", "logs", "uploads"],
    },
    {
      name: "kawoukeravore-whatsapp",
      script: "./apps/whatsapp-bot/src/index.js",
      cwd: "./",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "development",
      },
      env_production: {
        NODE_ENV: "production",
      },
      env_staging: {
        NODE_ENV: "staging",
      },
      log_file: "./logs/whatsapp-combined.log",
      out_file: "./logs/whatsapp-out.log",
      error_file: "./logs/whatsapp-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      max_memory_restart: "200M",
      restart_delay: 4000,
      max_restarts: 5,
      min_uptime: "10s",
      kill_timeout: 5000,
      autorestart: true,
      watch: false,
      ignore_watch: ["node_modules", "logs", "session"],
    },
  ],

  deploy: {
    production: {
      user: "www-data",
      host: ["kawoukeravore.top"],
      ref: "origin/main",
      repo: "https://github.com/cipfarorudy/kawoukeravore.git",
      path: "/var/www/kawoukeravore",
      ssh_options: "StrictHostKeyChecking=no",
      "pre-setup": "apt update && apt install git nodejs npm nginx -y",
      "post-setup": "npm install && npm run build",
      "pre-deploy-local": "echo 'Deploying to production...'",
      "post-deploy":
        "npm install && npm run build && pm2 reload ecosystem.config.js --env production && pm2 save",
      env: {
        NODE_ENV: "production",
        PORT: 4000,
      },
    },
    staging: {
      user: "www-data",
      host: ["staging.kawoukeravore.top"],
      ref: "origin/staging",
      repo: "https://github.com/cipfarorudy/kawoukeravore.git",
      path: "/var/www/kawoukeravore-staging",
      ssh_options: "StrictHostKeyChecking=no",
      "pre-setup": "apt update && apt install git nodejs npm nginx -y",
      "post-setup": "npm install && npm run build",
      "pre-deploy-local": "echo 'Deploying to staging...'",
      "post-deploy":
        "npm install && npm run build && pm2 reload ecosystem.config.js --env staging && pm2 save",
      env: {
        NODE_ENV: "staging",
        PORT: 4001,
      },
    },
  },
};
